travis:
  secure:
    BINSTAR_TOKEN: DeinkWFcTBH/n2UlFJFgRTCsezv+eW8XAYuAhPXSMwJRuy4K7OOo3BvuYKw2Q6yiG6g8xEnpJYHHuMbCOwoHgqJXQuLRmbfjKF4dKJ/NyOLSyUq+Amdx+CvFcS/TJwmYvT6Bu8RPL6mRUhfQ7BRkyzFQKEz8ALT0Fa9FfwUeF5TJT7GyLrrb02lR7W1XpaFhGpL2T7iLwBgicPrXFor09FcmMh+g2FBOwDaT25vzRxzwd7Hj6/1H6xV5z4WwwNhrGmD/Wb4f9eG4xGj0TSC3aiN9lPZRTICLLGvtER+JryH4TOWUDlgFazTrRcCXrvhIe5HCD3/YIDdrOtlRn6eY6O/96QuBLUSt3mQgm6jhSMYb8FFi85RTINeDMlf3lom7sRN6rTpLkwS6XTX+xrIGAqKRyezUNfH7J05J1cUGrZcAiJ38D5aqJXW9W9aikPJeUn+kz9wwOTN4jnk2/55HNGk4HNl70/Z1C3zV32b9F/gLIRyHSL7PrQ+RNldDqIuoVeQqKXCPo7Ua2NUrBe3zGj40voLRyVn7IWsCMAjfTO251C7Dzg40RTVfWdzr96IFAwqgczylNW4JGD9adG2qJX1CxFLeX80cG2dE08R1n2bw5aWpGo0q48LCSE+S5eiOX0urxTBxInu3QiD2HjbAforwRakH222KLYk03IlzMnU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
